### ISSUE TITLE
Titles Request

### ISSUE THREAD

**Issue by 4jakers18** [queenbiscuit311/SwitchRPCUpdated#1]
Would you be able to add 

- The Legend of Zelda: Tears of the Kingdom
- Monster Prom XXL
- Monster Camp XXL

**Comment by queenbiscuit311** [comment]
Somehow did not see this. I was planning to archive this repository and im extremely late, but i dont have much else to do so might as well add these titles.

**Comment by queenbiscuit311** [comment]
Should've done the job. I'll test it and add the rpc assets later.
